{% set version = "1.0.0" %}

package:
  name: swamp
  version: {{ version }}

source:
  git_url: https://github.com/fdchevalier/SWAMP.git
  #  sha256: f3832918bc3c66617f92e35f5d70729187676313caa60c187eb0f28b8fe5e3b5

requirements:
  run:
    - ffmpeg=4.2.3
    - hugin=2019.2.0
    - imagemagick=7.0.10_28
    - java-jdk
    - mysqlclient
    - pocl
    - python=3
    - r-base=3.6.3
    - r-magrittr=1.5
    - r-optparse=1.6.6
    - r-platetools=0.1.3
    - cellprofiler=4.2.1

about:
  home: https://github.com/fdchevalier/SWAMP
#   license: XXX
#   summary: 'XXX'
#   description: |
#     XXX 
  dev_url: https://github.com/fdchevalier/SWAMP
  doc_url: https://github.com/fdchevalier/SWAMP/wiki
